declare enum MappingPropertyEnum {
    MODE = "MODE",
    HISTORY_POLICY = "HISTORY_POLICY",
    MIN_INTERVAL_MS = "MIN_INTERVAL_MS",
    INTERVAL_MS = "INTERVAL_MS",
    CHANGE_MASK = "CHANGE_MASK",
    SKIP_FIRST_N_CHANGES = "SKIP_FIRST_N_CHANGES",
    TYPE = "TYPE",
    SEND_POLICY_MODE = "SEND_POLICY_MODE",
    DEADBAND = "DEADBAND",
    DEADBAND_PERCENT = "DEADBAND_PERCENT",
    LEVEL = "LEVEL",
    LEVEL_STRING = "LEVEL_STRING"
}
export default MappingPropertyEnum;
