import BasePropsHandler from './BasePropsHandler';
import IPropertyHandler from './IPropertyHandler';
export default class BaseGraphicPropsHandler extends BasePropsHandler {
    x: IPropertyHandler;
    y: IPropertyHandler;
    tx: IPropertyHandler;
    ty: IPropertyHandler;
    tz: IPropertyHandler;
    rx: IPropertyHandler;
    ry: IPropertyHandler;
    rz: IPropertyHandler;
    sx: IPropertyHandler;
    sy: IPropertyHandler;
    sz: IPropertyHandler;
    displayAsBillboard: IPropertyHandler;
    width: IPropertyHandler;
    height: IPropertyHandler;
    depth: IPropertyHandler;
    rectWidth: IPropertyHandler;
    rectHeight: IPropertyHandler;
    opacity: IPropertyHandler;
    scaleFactor: IPropertyHandler;
    keepAspectRatio: IPropertyHandler;
    bgColor: IPropertyHandler;
    placeholderWidth: IPropertyHandler;
    placeholderHeight: IPropertyHandler;
    topStroke: IPropertyHandler;
    bottomStroke: IPropertyHandler;
    leftStroke: IPropertyHandler;
    rightStroke: IPropertyHandler;
    topStrokeStyle: IPropertyHandler;
    bottomStrokeStyle: IPropertyHandler;
    leftStrokeStyle: IPropertyHandler;
    rightStrokeStyle: IPropertyHandler;
    topStrokeColor: IPropertyHandler;
    bottomStrokeColor: IPropertyHandler;
    leftStrokeColor: IPropertyHandler;
    rightStrokeColor: IPropertyHandler;
    showPermissions: IPropertyHandler;
    usePermissions: IPropertyHandler;
    enabledForGroups: IPropertyHandler;
    visibleForGroups: IPropertyHandler;
    disabled: IPropertyHandler;
    setDefaultAttributes(): void;
}
