import 'moment/locale/it';
import VueI18n, { DateTimeFormats } from 'vue-i18n';
import { RouteConfig } from 'vue-router';
import 'abortcontroller-polyfill/dist/abortcontroller-polyfill-only';
export declare const dateTimeFormats: DateTimeFormats;
export declare const i18n: VueI18n;
export declare function initCorvina(setupCorvinaInstance: any): Promise<void>;
export declare function logout(): void;
export declare function hasPermissionToRouteName(route: string): boolean;
export declare function hasPermissionToRoute(route: RouteConfig): boolean;
