import { PaginationRestDTO } from '@/interfaces/commons/pagination';
import { DeepSearchUserDTO, UserDeepSearchQueryParamsDTO, UserInDTO, UserOutDTO, UserQueryParamsDTO } from '@/interfaces/user';
import { UserGroupInDTO, UserGroupQueryParamsDTO, UserGroupOutDTO, UserGroupUpdateDTO, UserGroupMembershipRole } from '@/interfaces/userGroup';
import { RoleInDTO, RoleQueryParamsDTO, RoleOutDTO, DetailedRoleInDTO, RoleUpdateDTO } from '@/interfaces/role';
import { ApplicationPermissionQueryParamsDTO, ApplicationPermissionInDTO } from '@/interfaces/applicationpermission';
import { DeviceController } from '@/interfaces/devicecontroller';
import { ModelPathInDTO, ModelPathQueryParamsDTO, ModelPathOutDTO } from '@/interfaces/modelpath';
import { OrganizationInDTO, OrganizationOutDTO, OrganizationQueryParamsDTO, OrganizationUpdateDTO, OrganizationLoginInfoDTO } from '@/interfaces/organization';
import { SecurityPolicyQueryParamsDTO, SecurityPolicyOutDTO, SecurityPolicyInDTO } from '@/interfaces/securitypolicy';
import { DeviceQueryParamsDTO, DeviceRepositoryDTO, DeviceOutDTO } from '@/interfaces/device';
import { ApplicationOutDTO, ApplicationsQueryParamsDTO } from '@/interfaces/applications';
import { AccountDTO, AccountPatchDTO } from '@/interfaces/account';
export default interface ICorvinaCoreAxiosInstance {
    fetchUsers(organizationId: number, params?: UserQueryParamsDTO): Promise<PaginationRestDTO<UserInDTO>>;
    deepSearchUsers(params?: UserDeepSearchQueryParamsDTO): Promise<PaginationRestDTO<DeepSearchUserDTO>>;
    fetchUser(organizationId: number, userId: number): Promise<UserInDTO>;
    fetchUserByUsername(organizationId: number, username: string): Promise<UserInDTO>;
    createUser(organizationId: number, data: UserOutDTO): Promise<UserInDTO>;
    updateUser(organizationId: number, userId: number, newEmail: string | null, newPassword: string | null, passwordChangeInvitation: boolean | null, groupPoliciesEnabled: boolean | null): Promise<UserInDTO>;
    deleteUser(organizationId: number, userId: number): Promise<UserInDTO>;
    fetchUserGroups(organizationId: number, params?: UserGroupQueryParamsDTO): Promise<PaginationRestDTO<UserGroupInDTO>>;
    fetchUserGroup(organizationId: number, userGroupId: number): Promise<UserGroupInDTO>;
    createUserGroup(organizationId: number, data: UserGroupOutDTO): Promise<UserGroupInDTO>;
    editUserGroup(organizationId: number, userGroupId: number, data: UserGroupUpdateDTO): Promise<UserGroupInDTO>;
    addUserToGroup(organizationId: number, userGroupId: number, userId: number, role: UserGroupMembershipRole): Promise<UserGroupInDTO>;
    addRolesToGroup(organizationId: number, userGroupId: number, roleIds: number): Promise<UserGroupInDTO>;
    removeUserFromGroup(organizationId: number, userGroupId: number, userId: number): Promise<UserGroupInDTO>;
    removeRolesFromGroup(organizationId: number, userGroupId: number, roleIds: number): Promise<UserGroupInDTO>;
    deleteUserGroup(organizationId: number, userGroupId: number): Promise<UserGroupInDTO>;
    fetchRoles(organizationId: number, params?: RoleQueryParamsDTO): Promise<PaginationRestDTO<DetailedRoleInDTO>>;
    createModelPath(organizationId: number, data: ModelPathOutDTO): Promise<ModelPathInDTO>;
    fetchRole(organizationId: number, roleId: number): Promise<DetailedRoleInDTO>;
    createRole(organizationId: number, data: RoleOutDTO): Promise<RoleInDTO>;
    editRole(organizationId: number, roleId: number, data: RoleUpdateDTO): Promise<RoleInDTO>;
    deleteRole(organizationId: number, roleId: number): Promise<DetailedRoleInDTO>;
    fetchAllApplicationPermissions(params?: ApplicationPermissionQueryParamsDTO): Promise<PaginationRestDTO<ApplicationPermissionInDTO>>;
    fetchDeviceController(organizationId: number, deviceId: number): Promise<DeviceController>;
    fetchModelPaths(organizationId: number, params?: ModelPathQueryParamsDTO): Promise<PaginationRestDTO<ModelPathInDTO>>;
    createOrganization(data: OrganizationOutDTO): Promise<OrganizationInDTO>;
    createSubOrganization(organizationId: number, data: OrganizationOutDTO, options: {
        addDefaultRoles: boolean;
        waitLicenseManager: boolean;
    }): Promise<OrganizationInDTO>;
    fetchOrganization(organizationId: string): Promise<OrganizationInDTO>;
    updateSubOrganization(organizationId: number, data: OrganizationUpdateDTO): Promise<OrganizationInDTO>;
    deleteOrganization(organizationId: number): Promise<OrganizationInDTO>;
    fetchCurrentUserOrganizations(): Promise<OrganizationInDTO[]>;
    fetchOrganizations(organizationId: number, params?: OrganizationQueryParamsDTO): Promise<PaginationRestDTO<OrganizationInDTO>>;
    fetchSecurityPolicyGroups(organizationId: number, params?: SecurityPolicyQueryParamsDTO): Promise<PaginationRestDTO<SecurityPolicyInDTO>>;
    createSecurityPolicyGroup(organizationId: number, data: SecurityPolicyOutDTO): Promise<SecurityPolicyInDTO>;
    fetchSecurityPolicyGroup(organizationId: number, securityPolicyGroupId: number): Promise<SecurityPolicyInDTO>;
    updateSecurityPolicyGroup(organizationId: number, securityPolicyGroupId: number, data: SecurityPolicyOutDTO): Promise<SecurityPolicyInDTO>;
    deleteSecurityPolicyGroup(organizationId: number, securityPolicyGroupId: number): any;
    addDeviceToSecurityGroup(organizationId: number, securityPolicyGroupId: number, deviceId: number): Promise<SecurityPolicyInDTO>;
    removeDeviceFromSecurityGroup(organizationId: number, securityPolicyGroupId: number, deviceId: number): Promise<SecurityPolicyInDTO>;
    getLoginInfo(organization: string): Promise<OrganizationLoginInfoDTO>;
    fetchModelPathPermissions(organizationId: number, roleId: string, params?: any): any;
    fetchSecurityPolicyGroupsByParent(organizationId: number, securityPolicyGroupId: number, params?: SecurityPolicyQueryParamsDTO): Promise<PaginationRestDTO<SecurityPolicyInDTO>>;
    fetchDevices(organizationId: number, params?: DeviceQueryParamsDTO): Promise<PaginationRestDTO<DeviceRepositoryDTO>>;
    fetchDeviceByLabel(organizationId: number, deviceLabel: string): Promise<DeviceOutDTO>;
    fetchApplications(params?: ApplicationsQueryParamsDTO): Promise<PaginationRestDTO<ApplicationOutDTO>>;
    fetchAccount(): Promise<AccountDTO>;
    patchAccount(patch: AccountPatchDTO): Promise<void>;
    removeAccountCredential(id: string): Promise<void>;
    removeAccountSession(id: string): Promise<void>;
}
