import { Box3, BoxGeometry, Camera, CylinderGeometry, Intersection, Mesh, MeshBasicMaterial, MeshStandardMaterial, Object3D, Quaternion, Raycaster, Scene, SphereGeometry, Vector2, Vector3 } from "three";
import { OBB } from "three/examples/jsm/math/OBB";
type PlaneType = "ypos" | "yneg" | "xpos" | "xneg" | "zpos" | "zneg" | "yposxpos" | "ynegxpos" | "yposxneg" | "ynegxneg" | null;
interface ScaleGizmoPlane {
    topLeft?: Mesh;
    topRight?: Mesh;
    bottomLeft?: Mesh;
    bottomRight?: Mesh;
    plane?: Mesh;
}
type ScaleGizmoPlanes = {
    [key in PlaneType]: ScaleGizmoPlane;
};
export declare class ScaleGizmo {
    scene: Scene;
    gizmoColliderContainer: Object3D;
    box3: Box3;
    obb: OBB;
    attachedMesh: Mesh;
    transl: Vector3;
    rot: Quaternion;
    scale: Vector3;
    intersectedObject: any;
    objectContainer: Object3D;
    planes: ScaleGizmoPlanes;
    appliedOffset: Vector3;
    prevDistanceY: number;
    prevDistanceX: number;
    prevDistanceZ: number;
    selectedMode: "ypos" | "yneg" | "xpos" | "xneg" | "zpos" | "zneg" | "yposxpos" | "ynegxpos" | "yposxneg" | "ynegxneg" | null;
    canSwitchMode: boolean;
    gizmoHandlesContainer: Object3D;
    time: number;
    raycaster: Raycaster;
    mousedown: boolean;
    pointer: Vector2;
    camera: Camera;
    rightHandle: Mesh;
    topHandle: Mesh;
    scalePlane: Mesh;
    startPoint: Vector3;
    worldDirection: Quaternion;
    worldPos: Vector3;
    targetElement: HTMLCanvasElement;
    debugSphere: Mesh;
    pointerUpCallback: Function;
    pointerDownCallback: Function;
    leftHandle: Mesh;
    bottomHandle: Mesh;
    minScale: number;
    upLine: Mesh;
    bottomLine: Mesh<CylinderGeometry, MeshBasicMaterial>;
    startScale: Vector3;
    scaleWorldPos: Vector3;
    topleftHandle: Mesh;
    toprightHandle: Mesh<BoxGeometry, MeshBasicMaterial>;
    bottomleftHandle: Mesh<BoxGeometry, MeshBasicMaterial>;
    bottomrightHandle: Mesh<BoxGeometry, MeshBasicMaterial>;
    constructor(scene: Scene, camera: Camera, element: HTMLCanvasElement, pointerDownCallback: any, pointerUpCallback: any);
    onPointerDown(ev: PointerEvent): void;
    onMouseMove(ev: any): void;
    onMouseUp(ev: any): void;
    destroy(): void;
    createVector(pos: number[]): Vector3;
    attach(mesh: Mesh): void;
    detach(): void;
    deparent(): void;
    reparent(mesh: Mesh, corner?: PlaneType): void;
    calcOBB(mesh: Mesh, parent: Object3D): void;
    handleInput(ev: MouseEvent | KeyboardEvent): void;
    createHandles(): void;
    removeHandles(): void;
    updateHandles(): void;
    update(): void;
    checkSelectedControl(intersections: Intersection[]): void;
    cursorDistanceOnPlane(first?: boolean): void;
    updateScalePlane(mesh: Mesh, type: PlaneType): void;
    removeScalePlane(): void;
    createPos(position: Vector3, name: string): Mesh<SphereGeometry, MeshStandardMaterial>;
    createBox(position: Vector3, name: string, size?: number, color?: string): Mesh<BoxGeometry, MeshBasicMaterial>;
    updatePos(target: Object3D, position: Vector3): void;
    createLine(start: Vector3, end: Vector3, name: string): Mesh<CylinderGeometry, MeshBasicMaterial>;
}
export {};
