export declare enum PROJECT_SETTINGS_PANEL_MODE {
    DASHBOARD_EDITOR = "DASHBOARD_EDITOR",
    WIDGET_EDITOR = "WIDGET_EDITOR",
    DASHBOARD_LIST = "DASHBOARD_LIST",
    WIDGET_LIST = "WIDGET_LIST"
}
