import { CurrentUserOrganizations } from "../interfaces/organization";
declare const _default: {
    getCurrentOrganizationIOTEnabled(state: any): any;
    getCurrentOrganizationVPNEnabled(state: any): any;
    getCurrentOrganizationOPTRequired(state: any): any;
    getCurrentOrganizationVPNPairingMode(state: any): any;
    getCurrentFormUser(state: any): any;
    getCurrentFormGroup(state: any): any;
    getCurrentFormRole(state: any): any;
    getCurrentFormOrganization(state: any): any;
    getUsers(state: any): any;
    getUserGroups(state: any): any;
    getUserGroupsMine(state: any): any;
    getRoles(state: any): any;
    getDataRoles(state: any): any;
    getModelRoles(state: any): any;
    getOrganizations(state: any): CurrentUserOrganizations;
    getDevicePermissions(state: any): any;
    getCurrentUserOrg(state: any): any;
    getCurrentSubOrganizationController(state: any): any;
    getOrganizationController(state: any): (orgId: any) => any;
    getCurrentResources(state: any): any;
    getRouteQueryOrg(state: any): [string, string];
    getGlobalSelectorOrganizationsData(state: any): any;
    getGlobalSelectorOrganizationsIsLastPage(state: any): any;
    getGlobalSelectorOrganizationsPageNum(state: any): any;
    getHasRptToken(state: any): any;
    getLoginError(state: any): string | null;
    getAgreementsReminderShownInSession(state: any): any;
    getOrganizationAllowRegister(state: any, getters: any, rootState: any, rootGetters: any): boolean;
    getLoggedUser(state: any): any;
    getIsTrial(state: any): boolean;
    getTrialExpirationDate(state: any): any;
    getIsEditingSuborg(state: any): boolean;
    getSelectedOrganization(state: any): any;
    getSelectedSubOrganization(state: any): any;
    getAccessToken(state: any): any;
    getRefreshPermissionsRequired(state: any): number;
};
export default _default;
